#!/usr/bin/env bash
# Installs Nginx and configures it to return "Hello World!" at root path

# Update package list
apt-get update -y

# Install nginx without prompt
apt-get install nginx -y

# Replace default index page content with "Hello World!"
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# Start nginx (without systemctl)
if command -v service &> /dev/null; then
    service nginx start
else
    /etc/init.d/nginx start
fi
